server:
  port: 8080
  context-path: /mybatis
  error:
    path: /error
  session-timeout: 60
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transaction_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root

#druid
druid:
  url: jdbc:mysql://127.0.0.1:3306/transaction_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: root
#  初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
  initial-size: 1
#  最小连接池数量
  min-idle: 1
#  最大连接池数量
  max-active: 20
#  申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
  test-on-borrow: true
  stat:
    slowSqlMills: 500

mybatis:
  configLocation: classpath:mybatis.xml