
lock:
  enabled: true
  type: "zookeeper"
  zk:
    address: "172.16.143.102:2181,172.16.143.102:2182,172.16.143.102:2183"
    name-space: "lock_demo"
  prefix: "/"
#      auth-info:
#        auth: "test"
#        scheme: "test"
#      name-space: "dev"

