
lock:
  enabled: true
  type: "zk"
  zk:
    address: "172.16.143.102:2181,172.16.143.102:2182,172.16.143.102:2183"
  prefix: "lock_demo"
#      auth-info:
#        auth: "test"
#        scheme: "test"
#      name-space: "dev"

