spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: LEGACYHTML5
    check-template: true
    cache: false
    encoding: utf-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true