server.port: 1337

spring:
  application.name: leon
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    ip: localhost
    port: 3306
    name: spring
    username: root
    password: 123456
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.name}?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false

# 生成工具配置
cn.leon:
  moduleName: self-login
  tables: r_role_user,sys_menu,sys_user,sys_role,oauth_client_details  #逗号分隔
  java:
    rootPackage: cn.leon
    mybatis:
      domain: entity
      mapper: dao
      xml: mapper
#  view:
#    project:
#      enable: false
#      path: d://gitspace/self-login
#      js: js
#      html: module

#  generator:
#    project:
#      enable: false
#      name: leon
#      path: d://gitspace/springboot-study

